# Makefile autogenerated by Dyi on July 8, 2015
#
# Main target: all
# Sources:  src/ieee.js  src/index.ls 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-7wslgemy


.PHONY: c-2k4isqgd
c-2k4isqgd: lib/ieee.js


.PHONY: c-9jg453df
c-9jg453df: lib/index.ls


.PHONY: build
build: c-2k4isqgd c-9jg453df


.PHONY: test
test: k-sgi85jev k-wltckdvb


.PHONY: update
update: k-g4baa0i8


.PHONY: major
major: k-xb79105e k-x71jtp0v k-vr5g9pco


.PHONY: minor
minor: k-pef8b202 k-ihf62529 k-j343ievh


.PHONY: patch
patch: k-56oincek k-b6vhrkix k-u69c8kxc


.PHONY: prepare
prepare: lib




.PHONY: k-7wslgemy
k-7wslgemy:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-0j8j1pt9
k-0j8j1pt9:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-yhogycji
k-yhogycji:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-0j8j1pt9 
	make k-yhogycji  


.PHONY: k-sgi85jev
k-sgi85jev:  
	make all


.PHONY: k-wltckdvb
k-wltckdvb:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-g4baa0i8
k-g4baa0i8:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-xb79105e
k-xb79105e:  
	make all


.PHONY: k-x71jtp0v
k-x71jtp0v:  
	make docs


.PHONY: k-vr5g9pco
k-vr5g9pco:  
	./node_modules/.bin/xyz -i major


.PHONY: k-pef8b202
k-pef8b202:  
	make all


.PHONY: k-ihf62529
k-ihf62529:  
	make docs


.PHONY: k-j343ievh
k-j343ievh:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-56oincek
k-56oincek:  
	make all


.PHONY: k-b6vhrkix
k-b6vhrkix:  
	make docs


.PHONY: k-u69c8kxc
k-u69c8kxc:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/ieee.js
	rm -f lib/index.ls




lib/ieee.js: src/ieee.js 
	./node_modules/.bin/babel src/ieee.js -o ./lib/ieee.js

lib/index.ls: src/index.ls 
	./node_modules/.bin/lsc -o ./lib -c src/index.ls

lib: 
	mkdir -p lib

