# Makefile autogenerated by Dyi on July 8, 2015
#
# Main target: all
# Sources:  src/index.ls 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-ad55t3hr


.PHONY: c-yaoiaqx6
c-yaoiaqx6:


.PHONY: c-le8vajax
c-le8vajax: lib/index.ls


.PHONY: build
build: c-yaoiaqx6 c-le8vajax


.PHONY: test
test: k-x5c3ebtt k-rjfnko6t


.PHONY: update
update: k-g306jhnd


.PHONY: major
major: k-drl8b208 k-s2w2nck3 k-rej5a7hh


.PHONY: minor
minor: k-cu0mcop7 k-vkqbrqej k-77mt2dn6


.PHONY: patch
patch: k-t7pafcox k-lvk4lf06 k-rxq3kvw6


.PHONY: prepare
prepare: lib




.PHONY: k-ad55t3hr
k-ad55t3hr:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-moil5j4r
k-moil5j4r:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-u033xufu
k-u033xufu:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-moil5j4r 
	make k-u033xufu  


.PHONY: k-x5c3ebtt
k-x5c3ebtt:  
	make all


.PHONY: k-rjfnko6t
k-rjfnko6t:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-g306jhnd
k-g306jhnd:  
	make clean && ./node_modules/.bin/babel configure.js | node


.PHONY: k-drl8b208
k-drl8b208:  
	make all


.PHONY: k-s2w2nck3
k-s2w2nck3:  
	make docs


.PHONY: k-rej5a7hh
k-rej5a7hh:  
	./node_modules/.bin/xyz -i major


.PHONY: k-cu0mcop7
k-cu0mcop7:  
	make all


.PHONY: k-vkqbrqej
k-vkqbrqej:  
	make docs


.PHONY: k-77mt2dn6
k-77mt2dn6:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-t7pafcox
k-t7pafcox:  
	make all


.PHONY: k-lvk4lf06
k-lvk4lf06:  
	make docs


.PHONY: k-rxq3kvw6
k-rxq3kvw6:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  
	rm -f lib/index.ls




lib/index.ls: src/index.ls 
	./node_modules/.bin/lsc -o ./lib -c src/index.ls

lib: 
	mkdir -p lib

